FROM python:3.12.8-slim

WORKDIR /app

RUN pip install poetry

COPY  pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false

RUN poetry install --no-interaction --no-root

COPY . .

# EXPOSE 8081
# CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8081", "--reload"]